global:
  scrape_interval: 1s

scrape_configs:
- job_name: node
  static_configs:
  - targets: ['service:9100'] # NOT localhost since we named the host of service in docker-compose file

- job_name: pushgateway
  honor_labels: true  #加上此配置exporter节点上传数据中的一些标签将不会被pushgateway节点的相同标签覆盖
  static_configs:
    - targets: ['pushgateway:9091']
      labels:
        instance: pushgateway
